//
// Aster Communications Inc.
//
// Copyright (c) 2026 Aster Communications Inc.
//
// This file is part of this project.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.
//

package org.astermail.android.ui.mail

import androidx.annotation.StringRes
import org.astermail.android.R

data class emoji_entry(val glyph: String, val keywords: String)

data class emoji_group(@StringRes val title: Int, val entries: List<emoji_entry>)

val quick_reaction_emoji = listOf("👍", "❤️", "😂", "🎉", "😮", "😢")

private val smileys_and_people = listOf(
    emoji_entry("😀", "grin grinning smile happy"),
    emoji_entry("😃", "smile happy joy"),
    emoji_entry("😄", "smile happy laugh"),
    emoji_entry("😁", "beam grin happy"),
    emoji_entry("😆", "laugh squint happy"),
    emoji_entry("😅", "sweat smile nervous relief"),
    emoji_entry("🤣", "rolling floor laughing rofl lol"),
    emoji_entry("😂", "tears joy laughing lol crying"),
    emoji_entry("🙂", "slight smile"),
    emoji_entry("🙃", "upside down silly"),
    emoji_entry("😉", "wink flirt"),
    emoji_entry("😊", "blush smile shy"),
    emoji_entry("😇", "halo angel innocent"),
    emoji_entry("🥰", "hearts love adore"),
    emoji_entry("😍", "heart eyes love"),
    emoji_entry("🤩", "star struck amazed wow"),
    emoji_entry("😘", "kiss blow heart"),
    emoji_entry("😗", "kiss"),
    emoji_entry("😚", "kiss closed eyes"),
    emoji_entry("😋", "yum delicious tasty"),
    emoji_entry("😛", "tongue out"),
    emoji_entry("🤪", "zany crazy wild"),
    emoji_entry("🤑", "money mouth rich"),
    emoji_entry("🤗", "hug hugging"),
    emoji_entry("🤭", "oops hand over mouth giggle"),
    emoji_entry("🫡", "salute saluting"),
    emoji_entry("🤫", "shush quiet secret"),
    emoji_entry("🤔", "thinking hmm"),
    emoji_entry("🫢", "hand over mouth shock gasp"),
    emoji_entry("🤐", "zipper mouth silence"),
    emoji_entry("🤨", "raised eyebrow skeptical doubt"),
    emoji_entry("😐", "neutral face"),
    emoji_entry("😑", "expressionless"),
    emoji_entry("😶", "no mouth blank"),
    emoji_entry("😏", "smirk smug"),
    emoji_entry("😒", "unamused meh"),
    emoji_entry("🙄", "eye roll"),
    emoji_entry("😬", "grimace awkward"),
    emoji_entry("🤥", "lying nose"),
    emoji_entry("😌", "relieved calm"),
    emoji_entry("😔", "pensive sad"),
    emoji_entry("😪", "sleepy tired"),
    emoji_entry("😴", "sleeping zzz"),
    emoji_entry("😷", "mask sick"),
    emoji_entry("🤒", "thermometer sick fever"),
    emoji_entry("🤕", "bandage hurt"),
    emoji_entry("🤢", "nauseated sick"),
    emoji_entry("🤧", "sneeze"),
    emoji_entry("🥵", "hot heat sweating"),
    emoji_entry("🥶", "cold freezing"),
    emoji_entry("🥴", "woozy dizzy"),
    emoji_entry("😵", "knocked out dizzy"),
    emoji_entry("🤯", "mind blown exploding head"),
    emoji_entry("🤠", "cowboy hat"),
    emoji_entry("🥳", "party celebrate hat"),
    emoji_entry("🥸", "disguise incognito"),
    emoji_entry("😎", "sunglasses cool"),
    emoji_entry("🤓", "nerd glasses"),
    emoji_entry("🧐", "monocle inspect"),
    emoji_entry("😕", "confused"),
    emoji_entry("🫤", "diagonal mouth unsure"),
    emoji_entry("😟", "worried"),
    emoji_entry("🙁", "slight frown sad"),
    emoji_entry("☹️", "frown sad"),
    emoji_entry("😮", "surprised open mouth wow"),
    emoji_entry("😯", "hushed surprised"),
    emoji_entry("😲", "astonished shocked"),
    emoji_entry("😳", "flushed blush embarrassed"),
    emoji_entry("🥺", "pleading puppy eyes"),
    emoji_entry("🥹", "holding back tears"),
    emoji_entry("😦", "frowning shock"),
    emoji_entry("😧", "anguished"),
    emoji_entry("😨", "fearful scared"),
    emoji_entry("😰", "anxious sweat nervous"),
    emoji_entry("😥", "sad relieved disappointed"),
    emoji_entry("😢", "crying tear sad"),
    emoji_entry("😭", "sobbing loudly crying sad"),
    emoji_entry("😱", "screaming scared shock"),
    emoji_entry("😖", "confounded"),
    emoji_entry("😣", "persevere"),
    emoji_entry("😞", "disappointed sad"),
    emoji_entry("😓", "sweat"),
    emoji_entry("😩", "weary tired"),
    emoji_entry("😫", "exhausted tired"),
    emoji_entry("😤", "triumph steam angry"),
    emoji_entry("😡", "rage angry mad"),
    emoji_entry("😠", "angry mad"),
    emoji_entry("🤬", "cursing swearing angry"),
    emoji_entry("😈", "devil imp mischief"),
    emoji_entry("👿", "angry devil"),
    emoji_entry("💀", "skull dead"),
    emoji_entry("💩", "poop"),
    emoji_entry("🤡", "clown"),
    emoji_entry("👻", "ghost boo"),
    emoji_entry("👽", "alien"),
    emoji_entry("🤖", "robot bot"),
    emoji_entry("😺", "cat grin"),
    emoji_entry("😹", "cat laugh"),
    emoji_entry("😻", "cat heart eyes love"),
    emoji_entry("😽", "cat kiss"),
    emoji_entry("🙈", "see no evil monkey"),
    emoji_entry("🙉", "hear no evil monkey"),
    emoji_entry("🙊", "speak no evil monkey"),
    emoji_entry("👋", "wave hello hi bye"),
    emoji_entry("🤚", "raised back of hand"),
    emoji_entry("🖐️", "hand fingers splayed"),
    emoji_entry("✋", "raised hand stop"),
    emoji_entry("🖖", "vulcan spock"),
    emoji_entry("👌", "ok hand perfect"),
    emoji_entry("🤌", "pinched fingers"),
    emoji_entry("🤏", "pinching small"),
    emoji_entry("✌️", "victory peace"),
    emoji_entry("🤞", "crossed fingers luck hope"),
    emoji_entry("🫰", "index thumb crossed"),
    emoji_entry("🤟", "love you gesture"),
    emoji_entry("🤘", "rock on horns"),
    emoji_entry("🤙", "call me shaka"),
    emoji_entry("👈", "point left"),
    emoji_entry("👉", "point right"),
    emoji_entry("👆", "point up"),
    emoji_entry("👇", "point down"),
    emoji_entry("☝️", "index up"),
    emoji_entry("🫵", "pointing at you"),
    emoji_entry("👍", "thumbs up yes like approve"),
    emoji_entry("👎", "thumbs down no dislike"),
    emoji_entry("✊", "fist"),
    emoji_entry("👊", "punch fist bump"),
    emoji_entry("🤛", "left fist"),
    emoji_entry("🤜", "right fist"),
    emoji_entry("👏", "clap applause bravo"),
    emoji_entry("🙌", "raising hands celebrate praise"),
    emoji_entry("🫶", "heart hands love"),
    emoji_entry("👐", "open hands"),
    emoji_entry("🤲", "palms up together"),
    emoji_entry("🤝", "handshake deal agree"),
    emoji_entry("🙏", "pray thanks please"),
    emoji_entry("✍️", "writing hand"),
    emoji_entry("💅", "nail polish"),
    emoji_entry("💪", "muscle strong flex"),
    emoji_entry("🦾", "mechanical arm"),
    emoji_entry("👀", "eyes look watching"),
    emoji_entry("👁️", "eye"),
    emoji_entry("🧠", "brain smart"),
    emoji_entry("👄", "lips mouth"),
    emoji_entry("👶", "baby"),
    emoji_entry("🧒", "child"),
    emoji_entry("👦", "boy"),
    emoji_entry("👧", "girl"),
    emoji_entry("🧑", "person"),
    emoji_entry("👨", "man"),
    emoji_entry("👩", "woman"),
    emoji_entry("🧓", "older person"),
    emoji_entry("👷", "construction worker"),
    emoji_entry("🕵️", "detective spy"),
    emoji_entry("🧑‍💻", "technologist developer coder"),
    emoji_entry("🧙", "mage wizard"),
    emoji_entry("🦸", "superhero"),
    emoji_entry("🎅", "santa"),
    emoji_entry("🙇", "bowing sorry"),
    emoji_entry("🤦", "facepalm"),
    emoji_entry("🤷", "shrug dunno"),
    emoji_entry("🙋", "raising hand question"),
    emoji_entry("🙅", "no gesture stop"),
    emoji_entry("🙆", "ok gesture yes"),
    emoji_entry("💁", "sassy information desk"),
    emoji_entry("🙎", "pouting"),
    emoji_entry("🙍", "frowning person"),
    emoji_entry("🚶", "walking"),
    emoji_entry("🏃", "running run"),
    emoji_entry("💃", "dancer dancing"),
    emoji_entry("🕺", "man dancing"),
    emoji_entry("🧘", "yoga meditate lotus"),
    emoji_entry("🛌", "in bed sleeping"),
    emoji_entry("👫", "couple"),
    emoji_entry("💑", "couple heart love"),
    emoji_entry("💏", "kiss couple"),
    emoji_entry("👪", "family"),
)

private val animals_and_nature = listOf(
    emoji_entry("🐵", "monkey face"),
    emoji_entry("🐒", "monkey"),
    emoji_entry("🦍", "gorilla"),
    emoji_entry("🐶", "dog face puppy"),
    emoji_entry("🐕", "dog"),
    emoji_entry("🐩", "poodle"),
    emoji_entry("🐺", "wolf"),
    emoji_entry("🦊", "fox"),
    emoji_entry("🦝", "raccoon"),
    emoji_entry("🐱", "cat face kitten"),
    emoji_entry("🐈", "cat"),
    emoji_entry("🦁", "lion"),
    emoji_entry("🐯", "tiger face"),
    emoji_entry("🐅", "tiger"),
    emoji_entry("🐴", "horse face"),
    emoji_entry("🦄", "unicorn"),
    emoji_entry("🦓", "zebra"),
    emoji_entry("🦌", "deer"),
    emoji_entry("🐮", "cow face"),
    emoji_entry("🐷", "pig face"),
    emoji_entry("🐏", "ram"),
    emoji_entry("🐑", "sheep"),
    emoji_entry("🐐", "goat"),
    emoji_entry("🐪", "camel"),
    emoji_entry("🦒", "giraffe"),
    emoji_entry("🐘", "elephant"),
    emoji_entry("🦏", "rhinoceros"),
    emoji_entry("🐭", "mouse face"),
    emoji_entry("🐀", "rat"),
    emoji_entry("🐹", "hamster"),
    emoji_entry("🐰", "rabbit bunny"),
    emoji_entry("🐿️", "chipmunk squirrel"),
    emoji_entry("🦔", "hedgehog"),
    emoji_entry("🦇", "bat"),
    emoji_entry("🐻", "bear"),
    emoji_entry("🐨", "koala"),
    emoji_entry("🐼", "panda"),
    emoji_entry("🦘", "kangaroo"),
    emoji_entry("🐾", "paw prints"),
    emoji_entry("🦃", "turkey"),
    emoji_entry("🐔", "chicken"),
    emoji_entry("🐓", "rooster"),
    emoji_entry("🐣", "hatching chick"),
    emoji_entry("🐤", "baby chick"),
    emoji_entry("🐦", "bird"),
    emoji_entry("🐧", "penguin"),
    emoji_entry("🕊️", "dove peace"),
    emoji_entry("🦅", "eagle"),
    emoji_entry("🦆", "duck"),
    emoji_entry("🦉", "owl"),
    emoji_entry("🐸", "frog"),
    emoji_entry("🐊", "crocodile"),
    emoji_entry("🐢", "turtle"),
    emoji_entry("🦎", "lizard"),
    emoji_entry("🐍", "snake"),
    emoji_entry("🐲", "dragon face"),
    emoji_entry("🐳", "whale"),
    emoji_entry("🐬", "dolphin"),
    emoji_entry("🐟", "fish"),
    emoji_entry("🐠", "tropical fish"),
    emoji_entry("🦈", "shark"),
    emoji_entry("🐙", "octopus"),
    emoji_entry("🐚", "shell"),
    emoji_entry("🦀", "crab"),
    emoji_entry("🦐", "shrimp"),
    emoji_entry("🐜", "ant"),
    emoji_entry("🐝", "bee honeybee"),
    emoji_entry("🐞", "ladybug"),
    emoji_entry("🦋", "butterfly"),
    emoji_entry("🐛", "caterpillar bug"),
    emoji_entry("🕷️", "spider"),
    emoji_entry("🌸", "cherry blossom flower"),
    emoji_entry("💮", "white flower"),
    emoji_entry("🌹", "rose flower"),
    emoji_entry("🥀", "wilted flower"),
    emoji_entry("🌺", "hibiscus"),
    emoji_entry("🌻", "sunflower"),
    emoji_entry("🌷", "tulip"),
    emoji_entry("🌱", "seedling plant"),
    emoji_entry("🪴", "potted plant"),
    emoji_entry("🌲", "evergreen tree"),
    emoji_entry("🌳", "tree"),
    emoji_entry("🌴", "palm tree"),
    emoji_entry("🌵", "cactus"),
    emoji_entry("🌾", "sheaf rice"),
    emoji_entry("🌿", "herb leaf"),
    emoji_entry("☘️", "shamrock"),
    emoji_entry("🍀", "four leaf clover luck"),
    emoji_entry("🍁", "maple leaf"),
    emoji_entry("🍂", "fallen leaf"),
    emoji_entry("🍃", "leaf wind"),
    emoji_entry("🍄", "mushroom"),
    emoji_entry("🌍", "earth globe world"),
    emoji_entry("🌞", "sun face"),
    emoji_entry("☀️", "sun sunny"),
    emoji_entry("🌝", "full moon face"),
    emoji_entry("🌙", "crescent moon night"),
    emoji_entry("⭐", "star"),
    emoji_entry("🌟", "glowing star sparkle"),
    emoji_entry("✨", "sparkles magic"),
    emoji_entry("⚡", "lightning zap fast"),
    emoji_entry("🔥", "fire lit hot"),
    emoji_entry("💥", "collision boom"),
    emoji_entry("🌪️", "tornado"),
    emoji_entry("🌈", "rainbow"),
    emoji_entry("☁️", "cloud"),
    emoji_entry("🌧️", "rain"),
    emoji_entry("⛄", "snowman snow"),
    emoji_entry("❄️", "snowflake cold"),
    emoji_entry("🌊", "wave water ocean"),
    emoji_entry("💧", "droplet water"),
)

private val food_and_drink = listOf(
    emoji_entry("🍇", "grapes"),
    emoji_entry("🍈", "melon"),
    emoji_entry("🍉", "watermelon"),
    emoji_entry("🍊", "orange tangerine"),
    emoji_entry("🍋", "lemon"),
    emoji_entry("🍌", "banana"),
    emoji_entry("🍍", "pineapple"),
    emoji_entry("🥭", "mango"),
    emoji_entry("🍎", "red apple"),
    emoji_entry("🍏", "green apple"),
    emoji_entry("🍐", "pear"),
    emoji_entry("🍑", "peach"),
    emoji_entry("🍒", "cherries"),
    emoji_entry("🍓", "strawberry"),
    emoji_entry("🫐", "blueberries"),
    emoji_entry("🥝", "kiwi"),
    emoji_entry("🍅", "tomato"),
    emoji_entry("🫒", "olive"),
    emoji_entry("🥥", "coconut"),
    emoji_entry("🥑", "avocado"),
    emoji_entry("🍆", "eggplant"),
    emoji_entry("🥔", "potato"),
    emoji_entry("🥕", "carrot"),
    emoji_entry("🌽", "corn"),
    emoji_entry("🌶️", "hot pepper spicy"),
    emoji_entry("🫑", "bell pepper"),
    emoji_entry("🥒", "cucumber"),
    emoji_entry("🥬", "leafy green lettuce"),
    emoji_entry("🥦", "broccoli"),
    emoji_entry("🧄", "garlic"),
    emoji_entry("🧅", "onion"),
    emoji_entry("🥜", "peanuts"),
    emoji_entry("🌰", "chestnut"),
    emoji_entry("🍞", "bread"),
    emoji_entry("🥐", "croissant"),
    emoji_entry("🥖", "baguette"),
    emoji_entry("🥨", "pretzel"),
    emoji_entry("🥯", "bagel"),
    emoji_entry("🥞", "pancakes"),
    emoji_entry("🧇", "waffle"),
    emoji_entry("🧀", "cheese"),
    emoji_entry("🍖", "meat bone"),
    emoji_entry("🍗", "poultry leg chicken"),
    emoji_entry("🥩", "steak meat"),
    emoji_entry("🥓", "bacon"),
    emoji_entry("🍔", "hamburger burger"),
    emoji_entry("🍟", "fries"),
    emoji_entry("🍕", "pizza"),
    emoji_entry("🌭", "hot dog"),
    emoji_entry("🥪", "sandwich"),
    emoji_entry("🌮", "taco"),
    emoji_entry("🌯", "burrito"),
    emoji_entry("🥙", "stuffed flatbread"),
    emoji_entry("🥚", "egg"),
    emoji_entry("🍳", "cooking fried egg"),
    emoji_entry("🥘", "shallow pan paella"),
    emoji_entry("🍲", "stew soup"),
    emoji_entry("🥣", "bowl food"),
    emoji_entry("🥗", "salad"),
    emoji_entry("🍿", "popcorn"),
    emoji_entry("🧂", "salt"),
    emoji_entry("🥫", "canned food"),
    emoji_entry("🍱", "bento"),
    emoji_entry("🍘", "rice cracker"),
    emoji_entry("🍙", "rice ball"),
    emoji_entry("🍚", "rice"),
    emoji_entry("🍛", "curry"),
    emoji_entry("🍜", "ramen noodles"),
    emoji_entry("🍝", "spaghetti pasta"),
    emoji_entry("🍠", "sweet potato"),
    emoji_entry("🍣", "sushi"),
    emoji_entry("🍤", "fried shrimp"),
    emoji_entry("🍥", "fish cake"),
    emoji_entry("🥟", "dumpling"),
    emoji_entry("🥠", "fortune cookie"),
    emoji_entry("🍦", "soft ice cream"),
    emoji_entry("🍧", "shaved ice"),
    emoji_entry("🍨", "ice cream"),
    emoji_entry("🍩", "doughnut donut"),
    emoji_entry("🍪", "cookie"),
    emoji_entry("🎂", "birthday cake"),
    emoji_entry("🍰", "shortcake cake"),
    emoji_entry("🧁", "cupcake"),
    emoji_entry("🥧", "pie"),
    emoji_entry("🍫", "chocolate"),
    emoji_entry("🍬", "candy"),
    emoji_entry("🍭", "lollipop"),
    emoji_entry("🍯", "honey"),
    emoji_entry("🥛", "milk"),
    emoji_entry("☕", "coffee hot beverage"),
    emoji_entry("🫖", "teapot tea"),
    emoji_entry("🍵", "tea"),
    emoji_entry("🍾", "champagne bottle celebrate"),
    emoji_entry("🍷", "wine glass"),
    emoji_entry("🍸", "cocktail"),
    emoji_entry("🍹", "tropical drink"),
    emoji_entry("🍺", "beer"),
    emoji_entry("🍻", "clinking beers cheers"),
    emoji_entry("🥂", "clinking glasses cheers toast"),
    emoji_entry("🥃", "tumbler whisky"),
    emoji_entry("🥤", "cup straw"),
    emoji_entry("🧋", "bubble tea"),
    emoji_entry("🧃", "juice box"),
    emoji_entry("🧊", "ice"),
    emoji_entry("🍴", "fork knife"),
    emoji_entry("🍽️", "plate fork knife dinner"),
)

private val activity = listOf(
    emoji_entry("🎃", "jack o lantern halloween"),
    emoji_entry("🎄", "christmas tree"),
    emoji_entry("🎆", "fireworks"),
    emoji_entry("🎇", "sparkler"),
    emoji_entry("🧨", "firecracker"),
    emoji_entry("🎈", "balloon party"),
    emoji_entry("🎉", "party popper celebrate tada"),
    emoji_entry("🎊", "confetti ball celebrate"),
    emoji_entry("🎀", "ribbon bow"),
    emoji_entry("🎁", "gift present"),
    emoji_entry("🎫", "ticket"),
    emoji_entry("🏆", "trophy win"),
    emoji_entry("🏅", "sports medal"),
    emoji_entry("🥇", "first place gold"),
    emoji_entry("🥈", "second place silver"),
    emoji_entry("🥉", "third place bronze"),
    emoji_entry("⚽", "soccer football"),
    emoji_entry("⚾", "baseball"),
    emoji_entry("🥎", "softball"),
    emoji_entry("🏀", "basketball"),
    emoji_entry("🏐", "volleyball"),
    emoji_entry("🏈", "american football"),
    emoji_entry("🏉", "rugby"),
    emoji_entry("🎾", "tennis"),
    emoji_entry("🥏", "flying disc frisbee"),
    emoji_entry("🎳", "bowling"),
    emoji_entry("🏏", "cricket"),
    emoji_entry("🏑", "hockey"),
    emoji_entry("🏒", "ice hockey"),
    emoji_entry("🥍", "lacrosse"),
    emoji_entry("🏓", "ping pong table tennis"),
    emoji_entry("🏸", "badminton"),
    emoji_entry("🥊", "boxing glove"),
    emoji_entry("🥋", "martial arts"),
    emoji_entry("⛳", "golf"),
    emoji_entry("⛸️", "ice skate"),
    emoji_entry("🎣", "fishing"),
    emoji_entry("🤿", "diving mask"),
    emoji_entry("🎽", "running shirt"),
    emoji_entry("🎿", "skis"),
    emoji_entry("🛷", "sled"),
    emoji_entry("🎯", "bullseye target dart"),
    emoji_entry("🪀", "yo yo"),
    emoji_entry("🪁", "kite"),
    emoji_entry("🎱", "pool 8 ball"),
    emoji_entry("🔮", "crystal ball"),
    emoji_entry("🪄", "magic wand"),
    emoji_entry("🎮", "video game controller"),
    emoji_entry("🕹️", "joystick"),
    emoji_entry("🎰", "slot machine"),
    emoji_entry("🎲", "game die dice"),
    emoji_entry("🧩", "puzzle piece"),
    emoji_entry("🧸", "teddy bear"),
    emoji_entry("♠️", "spade"),
    emoji_entry("♥️", "heart suit"),
    emoji_entry("♦️", "diamond suit"),
    emoji_entry("♣️", "club suit"),
    emoji_entry("🃏", "joker card"),
    emoji_entry("🀄", "mahjong"),
    emoji_entry("🎭", "performing arts theater"),
    emoji_entry("🖼️", "framed picture art"),
    emoji_entry("🎨", "artist palette art"),
    emoji_entry("🧶", "yarn knit"),
    emoji_entry("🎤", "microphone sing"),
    emoji_entry("🎧", "headphone music"),
    emoji_entry("🎷", "saxophone"),
    emoji_entry("🎸", "guitar"),
    emoji_entry("🎹", "keyboard piano"),
    emoji_entry("🎺", "trumpet"),
    emoji_entry("🎻", "violin"),
    emoji_entry("🥁", "drum"),
    emoji_entry("🎼", "musical score"),
    emoji_entry("🎵", "music note"),
    emoji_entry("🎶", "music notes"),
)

private val travel_and_places = listOf(
    emoji_entry("🚗", "car automobile"),
    emoji_entry("🚕", "taxi"),
    emoji_entry("🚙", "suv"),
    emoji_entry("🚌", "bus"),
    emoji_entry("🏎️", "racing car"),
    emoji_entry("🚓", "police car"),
    emoji_entry("🚑", "ambulance"),
    emoji_entry("🚒", "fire engine"),
    emoji_entry("🚚", "truck"),
    emoji_entry("🚜", "tractor"),
    emoji_entry("🛵", "scooter motor"),
    emoji_entry("🏍️", "motorcycle"),
    emoji_entry("🚲", "bicycle bike"),
    emoji_entry("🛴", "kick scooter"),
    emoji_entry("🛹", "skateboard"),
    emoji_entry("🛣️", "motorway road"),
    emoji_entry("⛽", "fuel pump gas"),
    emoji_entry("🚨", "police light siren"),
    emoji_entry("🚦", "traffic light"),
    emoji_entry("🚧", "construction"),
    emoji_entry("🚂", "locomotive train"),
    emoji_entry("🚆", "train"),
    emoji_entry("🚇", "metro subway"),
    emoji_entry("🚊", "tram"),
    emoji_entry("🚄", "bullet train"),
    emoji_entry("🚁", "helicopter"),
    emoji_entry("✈️", "airplane flight travel"),
    emoji_entry("🛫", "departure takeoff"),
    emoji_entry("🛬", "arrival landing"),
    emoji_entry("🪂", "parachute"),
    emoji_entry("💺", "seat"),
    emoji_entry("🚀", "rocket launch"),
    emoji_entry("🛰️", "satellite"),
    emoji_entry("🛸", "flying saucer ufo"),
    emoji_entry("⛵", "sailboat"),
    emoji_entry("🚤", "speedboat"),
    emoji_entry("🛳️", "passenger ship cruise"),
    emoji_entry("⛴️", "ferry"),
    emoji_entry("🚢", "ship"),
    emoji_entry("⚓", "anchor"),
    emoji_entry("🛟", "life ring"),
    emoji_entry("🏖️", "beach"),
    emoji_entry("🏝️", "desert island"),
    emoji_entry("🏕️", "camping"),
    emoji_entry("⛺", "tent"),
    emoji_entry("🗺️", "world map"),
    emoji_entry("🧭", "compass"),
    emoji_entry("🗻", "mount fuji"),
    emoji_entry("⛰️", "mountain"),
    emoji_entry("🌋", "volcano"),
    emoji_entry("🏛️", "classical building"),
    emoji_entry("🏠", "house home"),
    emoji_entry("🏡", "house garden"),
    emoji_entry("🏢", "office building work"),
    emoji_entry("🏣", "post office"),
    emoji_entry("🏥", "hospital"),
    emoji_entry("🏦", "bank"),
    emoji_entry("🏨", "hotel"),
    emoji_entry("🏪", "convenience store"),
    emoji_entry("🏫", "school"),
    emoji_entry("🏭", "factory"),
    emoji_entry("🏯", "japanese castle"),
    emoji_entry("🏰", "castle"),
    emoji_entry("💒", "wedding"),
    emoji_entry("🗼", "tokyo tower"),
    emoji_entry("🗽", "statue of liberty"),
    emoji_entry("⛪", "church"),
    emoji_entry("🕌", "mosque"),
    emoji_entry("🛕", "hindu temple"),
    emoji_entry("🕍", "synagogue"),
    emoji_entry("⛲", "fountain"),
    emoji_entry("🌁", "foggy"),
    emoji_entry("🌃", "night stars"),
    emoji_entry("🌄", "sunrise mountains"),
    emoji_entry("🌅", "sunrise"),
    emoji_entry("🌆", "cityscape dusk"),
    emoji_entry("🌇", "sunset"),
    emoji_entry("🌉", "bridge night"),
    emoji_entry("🎠", "carousel horse"),
    emoji_entry("🎡", "ferris wheel"),
    emoji_entry("🎢", "roller coaster"),
)

private val objects = listOf(
    emoji_entry("⌚", "watch"),
    emoji_entry("📱", "mobile phone"),
    emoji_entry("📲", "phone call"),
    emoji_entry("💻", "laptop computer"),
    emoji_entry("⌨️", "keyboard"),
    emoji_entry("🖱️", "computer mouse"),
    emoji_entry("🖨️", "printer"),
    emoji_entry("🖥️", "desktop computer"),
    emoji_entry("💾", "floppy disk save"),
    emoji_entry("💿", "optical disk"),
    emoji_entry("🧮", "abacus"),
    emoji_entry("🎥", "movie camera film"),
    emoji_entry("🎬", "clapper board action"),
    emoji_entry("📺", "television tv"),
    emoji_entry("📷", "camera photo"),
    emoji_entry("📸", "camera flash"),
    emoji_entry("📹", "video camera"),
    emoji_entry("🔍", "search magnifying glass"),
    emoji_entry("🔬", "microscope"),
    emoji_entry("🔭", "telescope"),
    emoji_entry("📡", "satellite antenna"),
    emoji_entry("🕯️", "candle"),
    emoji_entry("💡", "light bulb idea"),
    emoji_entry("🔦", "flashlight"),
    emoji_entry("🏮", "red lantern"),
    emoji_entry("📕", "closed book"),
    emoji_entry("📖", "open book read"),
    emoji_entry("📚", "books library"),
    emoji_entry("📓", "notebook"),
    emoji_entry("📜", "scroll"),
    emoji_entry("📄", "page document file"),
    emoji_entry("📰", "newspaper news"),
    emoji_entry("🔖", "bookmark"),
    emoji_entry("🏷️", "label tag"),
    emoji_entry("💰", "money bag"),
    emoji_entry("🪙", "coin"),
    emoji_entry("💵", "dollar banknote"),
    emoji_entry("💳", "credit card"),
    emoji_entry("🧾", "receipt"),
    emoji_entry("✉️", "envelope email mail"),
    emoji_entry("📧", "email mail"),
    emoji_entry("📨", "incoming envelope"),
    emoji_entry("📩", "envelope arrow sent"),
    emoji_entry("📤", "outbox tray"),
    emoji_entry("📥", "inbox tray"),
    emoji_entry("📦", "package box"),
    emoji_entry("📫", "mailbox"),
    emoji_entry("✏️", "pencil"),
    emoji_entry("✒️", "black nib pen"),
    emoji_entry("🖊️", "pen"),
    emoji_entry("🖌️", "paintbrush"),
    emoji_entry("🖍️", "crayon"),
    emoji_entry("📝", "memo note write"),
    emoji_entry("💼", "briefcase work"),
    emoji_entry("📁", "folder file"),
    emoji_entry("📂", "open folder"),
    emoji_entry("📅", "calendar date"),
    emoji_entry("📆", "tear off calendar"),
    emoji_entry("🗒️", "spiral notepad"),
    emoji_entry("📋", "clipboard"),
    emoji_entry("📈", "chart increasing up"),
    emoji_entry("📉", "chart decreasing down"),
    emoji_entry("📊", "bar chart"),
    emoji_entry("📌", "pushpin"),
    emoji_entry("📍", "round pushpin location"),
    emoji_entry("📎", "paperclip attachment"),
    emoji_entry("📐", "triangular ruler"),
    emoji_entry("✂️", "scissors cut"),
    emoji_entry("🗄️", "file cabinet"),
    emoji_entry("🗑️", "wastebasket trash delete"),
    emoji_entry("🔒", "locked lock secure"),
    emoji_entry("🔓", "unlocked"),
    emoji_entry("🔐", "locked with key"),
    emoji_entry("🔑", "key"),
    emoji_entry("🔨", "hammer"),
    emoji_entry("🪓", "axe"),
    emoji_entry("🛠️", "tools settings"),
    emoji_entry("🔧", "wrench"),
    emoji_entry("🔩", "nut and bolt"),
    emoji_entry("⚙️", "gear settings"),
    emoji_entry("🧰", "toolbox"),
    emoji_entry("🧲", "magnet"),
    emoji_entry("🧪", "test tube"),
    emoji_entry("🧬", "dna"),
    emoji_entry("🔪", "kitchen knife"),
    emoji_entry("💊", "pill medicine"),
    emoji_entry("💉", "syringe"),
    emoji_entry("🩹", "adhesive bandage"),
    emoji_entry("🩺", "stethoscope"),
    emoji_entry("🚪", "door"),
    emoji_entry("🪟", "window"),
    emoji_entry("🛋️", "couch lamp"),
    emoji_entry("🛏️", "bed"),
    emoji_entry("🧹", "broom"),
    emoji_entry("🧺", "basket"),
    emoji_entry("🧼", "soap"),
    emoji_entry("🧯", "fire extinguisher"),
    emoji_entry("🛒", "shopping cart"),
    emoji_entry("🛍️", "shopping bags"),
    emoji_entry("👟", "running shoe sneaker"),
    emoji_entry("🎓", "graduation cap"),
    emoji_entry("👑", "crown"),
    emoji_entry("💍", "ring"),
    emoji_entry("💎", "gem stone diamond"),
    emoji_entry("👕", "t shirt"),
    emoji_entry("👖", "jeans"),
    emoji_entry("👗", "dress"),
    emoji_entry("👔", "necktie"),
    emoji_entry("🧥", "coat"),
    emoji_entry("👜", "handbag"),
    emoji_entry("🎒", "backpack"),
    emoji_entry("🕶️", "sunglasses"),
    emoji_entry("⏰", "alarm clock"),
    emoji_entry("⏳", "hourglass time"),
    emoji_entry("⌛", "hourglass done"),
    emoji_entry("🌡️", "thermometer"),
    emoji_entry("🧳", "luggage suitcase"),
    emoji_entry("🔔", "bell notification"),
    emoji_entry("🔕", "bell muted"),
    emoji_entry("📣", "megaphone announce"),
    emoji_entry("🔋", "battery"),
    emoji_entry("🔌", "plug"),
)

private val symbols = listOf(
    emoji_entry("❤️", "red heart love"),
    emoji_entry("🩷", "pink heart love"),
    emoji_entry("🧡", "orange heart"),
    emoji_entry("💛", "yellow heart"),
    emoji_entry("💚", "green heart"),
    emoji_entry("💙", "blue heart"),
    emoji_entry("💜", "purple heart"),
    emoji_entry("🖤", "black heart"),
    emoji_entry("🤍", "white heart"),
    emoji_entry("🤎", "brown heart"),
    emoji_entry("💔", "broken heart"),
    emoji_entry("❣️", "heart exclamation"),
    emoji_entry("💕", "two hearts"),
    emoji_entry("💞", "revolving hearts"),
    emoji_entry("💓", "beating heart"),
    emoji_entry("💗", "growing heart"),
    emoji_entry("💖", "sparkling heart"),
    emoji_entry("💘", "heart arrow cupid"),
    emoji_entry("💝", "heart with ribbon"),
    emoji_entry("💌", "love letter"),
    emoji_entry("💯", "hundred points perfect"),
    emoji_entry("💢", "anger"),
    emoji_entry("💫", "dizzy"),
    emoji_entry("💬", "speech balloon comment"),
    emoji_entry("💭", "thought balloon"),
    emoji_entry("💤", "zzz sleep"),
    emoji_entry("✔️", "check mark done yes"),
    emoji_entry("✅", "check button done yes"),
    emoji_entry("☑️", "checkbox checked"),
    emoji_entry("❌", "cross mark no wrong"),
    emoji_entry("❎", "cross mark button no"),
    emoji_entry("❗", "exclamation important"),
    emoji_entry("❓", "question"),
    emoji_entry("⁉️", "exclamation question"),
    emoji_entry("‼️", "double exclamation"),
    emoji_entry("⚠️", "warning caution"),
    emoji_entry("🚫", "prohibited no"),
    emoji_entry("💲", "dollar sign"),
    emoji_entry("🆕", "new"),
    emoji_entry("🆓", "free"),
    emoji_entry("🆗", "ok button"),
    emoji_entry("🆒", "cool button"),
    emoji_entry("🔝", "top arrow"),
    emoji_entry("🔙", "back arrow"),
    emoji_entry("🔜", "soon arrow"),
    emoji_entry("🔃", "clockwise arrows reload"),
    emoji_entry("🔄", "counterclockwise arrows refresh"),
    emoji_entry("🔀", "shuffle"),
    emoji_entry("🔁", "repeat loop"),
    emoji_entry("▶️", "play"),
    emoji_entry("⏩", "fast forward"),
    emoji_entry("⏸️", "pause"),
    emoji_entry("⏹️", "stop"),
    emoji_entry("⏪", "rewind"),
    emoji_entry("🔼", "up button"),
    emoji_entry("🔽", "down button"),
    emoji_entry("⬆️", "up arrow"),
    emoji_entry("⬇️", "down arrow"),
    emoji_entry("⬅️", "left arrow"),
    emoji_entry("➡️", "right arrow"),
    emoji_entry("↕️", "up down arrow"),
    emoji_entry("↔️", "left right arrow"),
    emoji_entry("↪️", "right hook arrow reply"),
    emoji_entry("↩️", "left hook arrow reply"),
    emoji_entry("☮️", "peace symbol"),
    emoji_entry("♻️", "recycling"),
    emoji_entry("🌐", "globe meridians internet"),
    emoji_entry("🔟", "keycap ten"),
    emoji_entry("⚫", "black circle"),
    emoji_entry("⚪", "white circle"),
    emoji_entry("🔴", "red circle"),
    emoji_entry("🟠", "orange circle"),
    emoji_entry("🟡", "yellow circle"),
    emoji_entry("🟢", "green circle"),
    emoji_entry("🔵", "blue circle"),
    emoji_entry("🟣", "purple circle"),
    emoji_entry("🟤", "brown circle"),
    emoji_entry("🔶", "large orange diamond"),
    emoji_entry("🔷", "large blue diamond"),
    emoji_entry("🔺", "red triangle up"),
    emoji_entry("🔻", "red triangle down"),
    emoji_entry("🔱", "trident"),
    emoji_entry("🏁", "chequered flag finish"),
    emoji_entry("🚩", "triangular flag"),
    emoji_entry("🎌", "crossed flags"),
    emoji_entry("🏴", "black flag"),
    emoji_entry("🏳️", "white flag"),
    emoji_entry("🏳️‍🌈", "rainbow flag pride"),
)

val emoji_catalog: List<emoji_group> = listOf(
    emoji_group(R.string.emoji_group_smileys, smileys_and_people),
    emoji_group(R.string.emoji_group_nature, animals_and_nature),
    emoji_group(R.string.emoji_group_food, food_and_drink),
    emoji_group(R.string.emoji_group_activity, activity),
    emoji_group(R.string.emoji_group_travel, travel_and_places),
    emoji_group(R.string.emoji_group_objects, objects),
    emoji_group(R.string.emoji_group_symbols, symbols),
)
