//
// Aster Communications Inc.
//
// Copyright (c) 2026 Aster Communications Inc.
//
// This file is part of this project.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.
//

package org.astermail.android.mail

val ASTER_DOMAIN_SUFFIXES: Set<String> = setOf(
    "astermail.org",
    "aster.cx",
)

val SOCIAL_DOMAIN_SUFFIXES: Set<String> = setOf(
    "facebook.com",
    "facebookmail.com",
    "fb.com",
    "messenger.com",
    "instagram.com",
    "linkedin.com",
    "linkedinmail.com",
    "twitter.com",
    "x.com",
    "t.co",
    "reddit.com",
    "redditmail.com",
    "redditinc.com",
    "tiktok.com",
    "tiktokv.com",
    "bytedance.com",
    "youtube.com",
    "pinterest.com",
    "pinterestmail.com",
    "discord.com",
    "discordapp.com",
    "snapchat.com",
    "snap.com",
    "quora.com",
    "meetup.com",
    "meetupstatic.com",
    "nextdoor.com",
    "tumblr.com",
    "twitch.tv",
    "mastodon.social",
    "mastodon.online",
    "bsky.app",
    "threads.net",
    "whatsapp.com",
    "telegram.org",
    "vk.com",
    "odnoklassniki.ru",
    "weibo.com",
    "line.me",
    "kakao.com",
    "kakaocorp.com",
    "vimeo.com",
    "flickr.com",
    "deviantart.com",
    "behance.net",
    "dribbble.com",
    "goodreads.com",
    "strava.com",
    "patreon.com",
    "medium.com",
    "xing.com",
    "soundcloud.com",
    "last.fm",
    "untappd.com",
    "tinder.com",
    "bumble.com",
    "hinge.co",
    "okcupid.com",
    "match.com",
    "eharmony.com",
    "plentyoffish.com",
    "grindr.com",
    "her.app",
    "tagged.com",
    "myspace.com",
    "clubhouse.com",
    "onlyfans.com",
    "wechat.com",
    "viber.com",
    "signal.org",
    "mewe.com",
    "gettr.com",
    "truthsocial.com",
    "parler.com",
    "gab.com",
    "minds.com",
    "ravelry.com",
    "letterboxd.com",
    "geni.com",
    "ancestry.com",
    "myheritage.com",
    "23andme.com",
    "familysearch.org",
    "nitter.net",
    "producthunt.com",
    "angel.co",
    "wellfound.com",
    "glassdoor.com",
    "indeed.com",
    "researchgate.net",
    "academia.edu",
)

val FORUM_DOMAIN_SUFFIXES: Set<String> = setOf(
    "googlegroups.com",
    "groups.io",
    "discourse.org",
    "discoursemail.com",
    "listserv.com",
    "freelists.org",
    "yahoogroups.com",
    "python.org",
    "sourceforge.net",
    "narkive.com",
    "librelist.com",
    "mailman3.com",
    "stackexchange.com",
    "stackoverflow.email",
    "stackoverflow.com",
    "phpbb.com",
    "vbulletin.com",
    "xenforo.com",
    "invisioncommunity.com",
    "proboards.com",
    "flarum.org",
    "nabble.com",
    "gnu.org",
    "kernel.org",
    "apache.org",
    "eclipse.org",
    "w3.org",
    "ietf.org",
    "lists.debian.org",
    "lists.ubuntu.com",
    "lists.freedesktop.org",
    "spiceworks.com",
    "avforums.com",
    "reddit.com",
)

val FINANCE_DOMAIN_SUFFIXES: Set<String> = setOf(
    "paypal.com",
    "paypal.co.uk",
    "stripe.com",
    "squareup.com",
    "square.com",
    "venmo.com",
    "cash.app",
    "block.xyz",
    "wise.com",
    "transferwise.com",
    "revolut.com",
    "n26.com",
    "monzo.com",
    "starlingbank.com",
    "coinbase.com",
    "kraken.com",
    "gemini.com",
    "binance.com",
    "crypto.com",
    "blockchain.com",
    "robinhood.com",
    "webull.com",
    "chime.com",
    "current.com",
    "varo.com",
    "plaid.com",
    "intuit.com",
    "quickbooks.com",
    "mint.com",
    "creditkarma.com",
    "sofi.com",
    "affirm.com",
    "klarna.com",
    "afterpay.com",
    "zip.co",
    "sezzle.com",
    "paysafecard.com",
    "skrill.com",
    "neteller.com",
    "payoneer.com",
    "adyen.com",
    "worldpay.com",
    "checkout.com",
    "braintreepayments.com",
    "authorize.net",
    "zelle.com",
    "xoom.com",
    "westernunion.com",
    "moneygram.com",
    "remitly.com",
    "wirebarley.com",
    "acorns.com",
    "wealthfront.com",
    "betterment.com",
    "publicinvest.com",
    "public.com",
    "m1finance.com",
    "ramp.com",
    "brex.com",
    "mercury.com",
    "bill.com",
    "gusto.com",
    "adp.com",
    "paychex.com",
    "expensify.com",
    "freshbooks.com",
    "xero.com",
    "wave.com",
    "waveapps.com",
    "chase.com",
    "bankofamerica.com",
    "wellsfargo.com",
    "citi.com",
    "citibank.com",
    "capitalone.com",
    "americanexpress.com",
    "aexp.com",
    "discover.com",
    "usbank.com",
    "pnc.com",
    "truist.com",
    "regions.com",
    "keybank.com",
    "huntington.com",
    "fifththird.com",
    "tdbank.com",
    "td.com",
    "rbc.com",
    "scotiabank.com",
    "bmo.com",
    "cibc.com",
    "hsbc.com",
    "hsbc.co.uk",
    "barclays.com",
    "barclays.co.uk",
    "lloydsbank.com",
    "natwest.com",
    "santander.com",
    "santander.co.uk",
    "bbva.com",
    "bnpparibas.com",
    "societegenerale.com",
    "deutsche-bank.de",
    "db.com",
    "commerzbank.de",
    "ing.com",
    "abnamro.com",
    "rabobank.com",
    "creditsuisse.com",
    "ubs.com",
    "unicredit.eu",
    "intesasanpaolo.com",
    "nordea.com",
    "danskebank.com",
    "seb.se",
    "swedbank.com",
    "dbs.com",
    "ocbc.com",
    "uob.com.sg",
    "standardchartered.com",
    "mufg.jp",
    "smbc.co.jp",
    "mizuhobank.com",
    "icbc.com.cn",
    "ccb.com",
    "boc.cn",
    "hdfcbank.com",
    "icicibank.com",
    "sbi.co.in",
    "axisbank.com",
    "kotak.com",
    "commbank.com.au",
    "nab.com.au",
    "westpac.com.au",
    "anz.com",
    "ally.com",
    "schwab.com",
    "fidelity.com",
    "vanguard.com",
    "etrade.com",
    "morganstanley.com",
    "goldmansachs.com",
    "marcus.com",
    "synchronybank.com",
    "synchrony.com",
    "navyfederal.org",
    "usaa.com",
    "penfed.org",
    "visa.com",
    "mastercard.com",
    "irs.gov",
    "ssa.gov",
    "turbotax.com",
    "hrblock.com",
    "creditsesame.com",
    "experian.com",
    "equifax.com",
    "transunion.com",
    "myfico.com",
    "prosper.com",
    "lendingclub.com",
    "upstart.com",
    "salliemae.com",
    "navient.com",
    "studentaid.gov",
    "geico.com",
    "progressive.com",
    "statefarm.com",
    "allstate.com",
    "libertymutual.com",
    "nationwide.com",
    "farmers.com",
    "usaainsurance.com",
)

val TRAVEL_DOMAIN_SUFFIXES: Set<String> = setOf(
    "uber.com",
    "ubereats.com",
    "lyft.com",
    "doordash.com",
    "grubhub.com",
    "seamless.com",
    "postmates.com",
    "instacart.com",
    "deliveroo.com",
    "just-eat.com",
    "justeat.co.uk",
    "gopuff.com",
    "olacabs.com",
    "grab.com",
    "didiglobal.com",
    "bolt.eu",
    "gett.com",
    "freenow.com",
    "airbnb.com",
    "vrbo.com",
    "homeaway.com",
    "booking.com",
    "expedia.com",
    "hotels.com",
    "hotwire.com",
    "priceline.com",
    "kayak.com",
    "skyscanner.com",
    "tripadvisor.com",
    "trivago.com",
    "orbitz.com",
    "travelocity.com",
    "cheaptickets.com",
    "agoda.com",
    "trip.com",
    "ctrip.com",
    "makemytrip.com",
    "goibibo.com",
    "traveloka.com",
    "hostelworld.com",
    "marriott.com",
    "hilton.com",
    "ihg.com",
    "hyatt.com",
    "wyndhamhotels.com",
    "choicehotels.com",
    "accor.com",
    "bestwestern.com",
    "radissonhotels.com",
    "fourseasons.com",
    "ritzcarlton.com",
    "starwoodhotels.com",
    "oyorooms.com",
    "delta.com",
    "united.com",
    "aa.com",
    "southwest.com",
    "jetblue.com",
    "alaskaair.com",
    "spirit.com",
    "frontierairlines.com",
    "allegiantair.com",
    "hawaiianairlines.com",
    "ryanair.com",
    "easyjet.com",
    "wizzair.com",
    "lufthansa.com",
    "britishairways.com",
    "airfrance.com",
    "klm.com",
    "iberia.com",
    "alitalia.com",
    "swiss.com",
    "austrian.com",
    "turkishairlines.com",
    "emirates.com",
    "qatarairways.com",
    "etihad.com",
    "singaporeair.com",
    "cathaypacific.com",
    "japanairlines.com",
    "jal.com",
    "ana.co.jp",
    "koreanair.com",
    "airchina.com",
    "airindia.com",
    "vistara.com",
    "indigo.in",
    "qantas.com",
    "virginaustralia.com",
    "airnz.co.nz",
    "aircanada.com",
    "westjet.com",
    "avianca.com",
    "latam.com",
    "aeromexico.com",
    "flysas.com",
    "finnair.com",
    "icelandair.com",
    "tap.pt",
    "rentalcars.com",
    "hertz.com",
    "avis.com",
    "budget.com",
    "enterprise.com",
    "nationalcar.com",
    "alamo.com",
    "sixt.com",
    "europcar.com",
    "zipcar.com",
    "turo.com",
    "getaround.com",
    "carnival.com",
    "royalcaribbean.com",
    "norwegiancruiseline.com",
    "princess.com",
    "celebritycruises.com",
    "amtrak.com",
    "eurostar.com",
    "raileurope.com",
    "trainline.com",
    "greyhound.com",
    "megabus.com",
    "flixbus.com",
    "opentable.com",
    "resy.com",
    "yelp.com",
)

val SHOPPING_DOMAIN_SUFFIXES: Set<String> = setOf(
    "amazon.com",
    "amazon.co.uk",
    "amazon.de",
    "amazon.ca",
    "amazon.in",
    "amazon.co.jp",
    "amazon.com.au",
    "ebay.com",
    "ebay.co.uk",
    "etsy.com",
    "walmart.com",
    "target.com",
    "bestbuy.com",
    "costco.com",
    "samsclub.com",
    "aliexpress.com",
    "alibaba.com",
    "wayfair.com",
    "shein.com",
    "wish.com",
    "zappos.com",
    "chewy.com",
    "newegg.com",
    "homedepot.com",
    "lowes.com",
    "ikea.com",
    "shopify.com",
    "temu.com",
    "overstock.com",
    "kohls.com",
    "macys.com",
    "nordstrom.com",
    "jcpenney.com",
    "gap.com",
    "oldnavy.com",
    "bananarepublic.com",
    "hm.com",
    "zara.com",
    "uniqlo.com",
    "asos.com",
    "boohoo.com",
    "nike.com",
    "adidas.com",
    "underarmour.com",
    "footlocker.com",
    "sephora.com",
    "ulta.com",
    "bathandbodyworks.com",
    "victoriassecret.com",
    "carters.com",
    "gymboree.com",
    "toysrus.com",
    "lego.com",
    "petco.com",
    "petsmart.com",
    "staples.com",
    "officedepot.com",
    "michaels.com",
    "joann.com",
    "hobbylobby.com",
    "wholefoodsmarket.com",
    "kroger.com",
    "safeway.com",
    "albertsons.com",
    "publix.com",
    "traderjoes.com",
    "aldi.us",
    "cvs.com",
    "walgreens.com",
    "riteaid.com",
    "gnc.com",
    "vitacost.com",
    "iherb.com",
    "flipkart.com",
    "myntra.com",
    "meesho.com",
    "snapdeal.com",
    "jd.com",
    "tmall.com",
    "taobao.com",
    "pinduoduo.com",
    "rakuten.com",
    "mercadolibre.com",
    "mercadolivre.com.br",
    "coupang.com",
    "gmarket.co.kr",
    "lazada.com",
    "shopee.com",
    "carousell.com",
    "otto.de",
    "zalando.com",
    "cdiscount.com",
    "fnac.com",
    "argos.co.uk",
    "very.co.uk",
    "johnlewis.com",
    "next.co.uk",
    "marksandspencer.com",
    "currys.co.uk",
    "b-and-q.com",
    "screwfix.com",
    "chemistwarehouse.com.au",
    "harveynorman.com.au",
    "jbhifi.com.au",
    "canadiantire.ca",
    "bestbuy.ca",
    "sportchek.ca",
    "dickssportinggoods.com",
    "rei.com",
    "backcountry.com",
    "patagonia.com",
    "llbean.com",
    "carhartt.com",
    "vans.com",
    "converse.com",
    "crocs.com",
    "warbyparker.com",
    "glossier.com",
    "colourpop.com",
    "fentybeauty.com",
    "brooklinen.com",
    "casper.com",
    "purple.com",
    "wayfair.co.uk",
    "westelm.com",
    "potterybarn.com",
    "cratebarrel.com",
    "worldmarket.com",
    "containerstore.com",
    "bedbathandbeyond.com",
    "1800flowers.com",
    "ftd.com",
    "proflowers.com",
    "shutterfly.com",
    "snapfish.com",
    "vistaprint.com",
    "moo.com",
    "stockx.com",
    "goat.com",
    "grailed.com",
    "poshmark.com",
    "thredup.com",
    "therealreal.com",
    "depop.com",
    "vinted.com",
    "offerup.com",
    "letgo.com",
    "craigslist.org",
)

val UPDATES_DOMAIN_SUFFIXES: Set<String> = setOf(
    "github.com",
    "gitlab.com",
    "bitbucket.org",
    "atlassian.net",
    "atlassian.com",
    "jira.com",
    "npmjs.com",
    "vercel.com",
    "netlify.com",
    "cloudflare.com",
    "digitalocean.com",
    "linode.com",
    "heroku.com",
    "docker.com",
    "pypi.org",
    "jetbrains.com",
    "aws.amazon.com",
    "amazonaws.com",
    "azure.com",
    "cloud.google.com",
    "googlecloud.com",
    "oracle.com",
    "ibm.com",
    "salesforce.com",
    "sap.com",
    "workday.com",
    "servicenow.com",
    "zendesk.com",
    "freshworks.com",
    "hubspot.com",
    "mailchimp.com",
    "sendinblue.com",
    "intercom.com",
    "intercom.io",
    "twilio.com",
    "segment.com",
    "datadoghq.com",
    "newrelic.com",
    "pagerduty.com",
    "opsgenie.com",
    "statuspage.io",
    "figma.com",
    "canva.com",
    "adobe.com",
    "miro.com",
    "loom.com",
    "airtable.com",
    "monday.com",
    "clickup.com",
    "linear.app",
    "basecamp.com",
    "wrike.com",
    "smartsheet.com",
    "coda.io",
    "confluence.com",
    "apple.com",
    "microsoft.com",
    "office.com",
    "office365.com",
    "google.com",
    "dropbox.com",
    "box.com",
    "notion.so",
    "evernote.com",
    "zoom.us",
    "webex.com",
    "gotomeeting.com",
    "teams.microsoft.com",
    "calendly.com",
    "docusign.net",
    "docusign.com",
    "hellosign.com",
    "adobesign.com",
    "slack.com",
    "asana.com",
    "trello.com",
    "todoist.com",
    "grammarly.com",
    "lastpass.com",
    "bitwarden.com",
    "okta.com",
    "auth0.com",
    "duosecurity.com",
    "1password.com",
    "dashlane.com",
    "yubico.com",
    "nordvpn.com",
    "expressvpn.com",
    "protonvpn.com",
    "surfshark.com",
    "verizon.com",
    "verizonwireless.com",
    "att.com",
    "t-mobile.com",
    "sprint.com",
    "comcast.com",
    "xfinity.com",
    "spectrum.com",
    "charter.com",
    "cox.com",
    "centurylink.com",
    "frontier.com",
    "vodafone.com",
    "vodafone.co.uk",
    "ee.co.uk",
    "o2.co.uk",
    "three.co.uk",
    "orange.fr",
    "telefonica.com",
    "movistar.com",
    "telstra.com.au",
    "optus.com.au",
    "rogers.com",
    "bell.ca",
    "telus.com",
    "deutschetelekom.com",
    "telekom.de",
    "duke-energy.com",
    "pge.com",
    "coned.com",
    "nationalgrid.com",
    "sce.com",
    "usps.gov",
    "dmv.ca.gov",
    "medicare.gov",
    "healthcare.gov",
    "gov.uk",
    "canada.ca",
    "netflix.com",
    "hulu.com",
    "disneyplus.com",
    "hbomax.com",
    "max.com",
    "paramountplus.com",
    "peacocktv.com",
    "spotify.com",
    "pandora.com",
    "audible.com",
    "kindle.com",
    "playstation.com",
    "xbox.com",
    "nintendo.com",
    "steampowered.com",
    "epicgames.com",
    "ea.com",
    "blizzard.com",
    "riotgames.com",
    "ups.com",
    "fedex.com",
    "usps.com",
    "dhl.com",
    "ontrac.com",
    "canadapost.ca",
    "royalmail.com",
    "auspost.com.au",
    "purolator.com",
    "gls-group.eu",
    "hermesworld.com",
    "evri.com",
    "yodel.co.uk",
    "aramex.com",
    "tnt.com",
    "lasership.com",
    "correos.es",
    "postnl.nl",
    "deutschepost.de",
    "chinapost.com.cn",
    "sf-express.com",
    "japanpost.jp",
    "shipstation.com",
    "shippo.com",
    "easypost.com",
)

val MARKETING_DOMAIN_SUFFIXES: Set<String> = setOf(
    "mcsv.net",
    "mcdlv.net",
    "rsgsv.net",
    "mailchimpapp.com",
    "mcsignup.com",
    "mctxapp.net",
    "list-manage.com",
    "klaviyomail.com",
    "kmail-lists.com",
    "klclick.com",
    "klaviyo.com",
    "rs6.net",
    "constantcontact.com",
    "ccsend.com",
    "hubspotemail.net",
    "hs-send.com",
    "hubspotlinks.com",
    "mktomail.com",
    "mktdns.com",
    "marketo.com",
    "createsend.com",
    "createsend1.com",
    "cmail19.com",
    "cmail20.com",
    "campaignmonitor.com",
    "getresponse.com",
    "gr-message.com",
    "aweber.com",
    "activehosted.com",
    "activecampaign.com",
    "sendinblue.com",
    "sibautomation.com",
    "brevo.com",
    "omnisend.com",
    "getdrip.com",
    "drip.com",
    "exct.net",
    "exacttarget.com",
    "salesforce-communities.com",
    "sailthru.com",
    "iterable.com",
    "iterable-mail.com",
    "braze.com",
    "braze.eu",
    "customeriomail.com",
    "customer.io",
    "mailerlite.com",
    "ml-attach.com",
    "convertkit.com",
    "convertkitmail.com",
    "ck.page",
    "moosend.com",
    "benchmarkemail.com",
    "verticalresponse.com",
    "madmimi.com",
    "constantcontactpages.com",
    "responsys.net",
    "oracleoutreach.com",
    "listrak.com",
    "silverpop.com",
    "bronto.com",
    "cheetahmail.com",
    "yesmail.com",
    "epsilon.com",
)

val BULK_INFRA_DOMAIN_SUFFIXES: Set<String> = setOf(
    "sendgrid.net",
    "sendgrid.com",
    "mailgun.org",
    "mailgun.net",
    "amazonses.com",
    "sparkpostmail.com",
    "sparkpost.com",
    "postmarkapp.com",
    "mtasv.net",
    "mailjet.com",
    "mandrillapp.com",
    "socketlabs.com",
    "pepipost.com",
    "elasticemail.com",
    "smtp.com",
    "smtp2go.com",
    "mailtrap.io",
    "mailersend.com",
    "postal.chef",
    "sendpulse.com",
    "cakemail.com",
    "e2ma.net",
    "acemlna.com",
    "acemlnb.com",
)

val BULK_SENDER_LOCALPARTS: Set<String> = setOf(
    "no-reply",
    "noreply",
    "no.reply",
    "noreplies",
    "donotreply",
    "do-not-reply",
    "do_not_reply",
    "notifications",
    "notification",
    "notify",
    "updates",
    "update",
    "alerts",
    "alert",
    "info",
    "news",
    "newsletter",
    "newsletters",
    "marketing",
    "offers",
    "deals",
    "promo",
    "promotions",
    "hello",
    "hi",
    "team",
    "support",
    "help",
    "contact",
    "mailer",
    "mailer-daemon",
    "bounce",
    "bounces",
    "receipts",
    "receipt",
    "billing",
    "invoice",
    "invoices",
    "account",
    "accounts",
    "members",
    "member",
    "community",
    "digest",
    "auto",
    "automated",
    "system",
    "service",
    "services",
    "email",
    "mail",
    "post",
    "messages",
    "reply",
    "store",
    "shop",
    "orders",
    "order",
    "confirm",
    "confirmation",
    "security",
    "care",
    "customerservice",
    "customer-service",
    "feedback",
    "survey",
    "rewards",
    "loyalty",
    "vip",
    "insider",
    "insiders",
    "welcome",
    "onboarding",
    "statements",
    "statement",
    "payments",
    "payment",
    "shipping",
    "delivery",
    "tracking",
    "booking",
    "bookings",
    "reservations",
    "reservation",
    "verify",
    "verification",
    "password",
    "login",
    "signin",
    "twofactor",
    "2fa",
    "otp",
)

val PROMOTIONS_SUBJECT_PATTERNS: List<Regex> = listOf(
    Regex("""\b\d{1,3}\s*%\s*off\b""", RegexOption.IGNORE_CASE),
    Regex("""\b\d{1,3}\s*%\s*(?:back|cash\s*back)\b""", RegexOption.IGNORE_CASE),
    Regex("""\bsale\b""", RegexOption.IGNORE_CASE),
    Regex("""\bdeal(s)?\b""", RegexOption.IGNORE_CASE),
    Regex("""\bdiscount(s)?\b""", RegexOption.IGNORE_CASE),
    Regex("""\bcoupon(s)?\b""", RegexOption.IGNORE_CASE),
    Regex("""\bpromo(?:\s*code)?\b""", RegexOption.IGNORE_CASE),
    Regex("""\boffer(s)?\b""", RegexOption.IGNORE_CASE),
    Regex("""\bsave\s+(?:up\s+to\s+)?\$?\d""", RegexOption.IGNORE_CASE),
    Regex("""\blimited\s+time\b""", RegexOption.IGNORE_CASE),
    Regex("""\bblack\s+friday\b""", RegexOption.IGNORE_CASE),
    Regex("""\bcyber\s+monday\b""", RegexOption.IGNORE_CASE),
    Regex("""\bflash\s+sale\b""", RegexOption.IGNORE_CASE),
    Regex("""\bfree\s+shipping\b""", RegexOption.IGNORE_CASE),
    Regex("""\bnew\s+arrivals?\b""", RegexOption.IGNORE_CASE),
    Regex("""\bexclusive\b""", RegexOption.IGNORE_CASE),
    Regex("""\bclearance\b""", RegexOption.IGNORE_CASE),
    Regex("""\bdon'?t\s+miss\b""", RegexOption.IGNORE_CASE),
    Regex("""\blast\s+chance\b""", RegexOption.IGNORE_CASE),
    Regex("""\bact\s+now\b""", RegexOption.IGNORE_CASE),
    Regex("""\bshop\s+now\b""", RegexOption.IGNORE_CASE),
    Regex("""\bbuy\s+(?:now|one)\b""", RegexOption.IGNORE_CASE),
    Regex("""\bbogo\b""", RegexOption.IGNORE_CASE),
    Regex("""\bmembers?\s+only\b""", RegexOption.IGNORE_CASE),
    Regex("""\bearly\s+access\b""", RegexOption.IGNORE_CASE),
    Regex("""\bgiveaway\b""", RegexOption.IGNORE_CASE),
    Regex("""\bbest\s+(?:price|deal)\b""", RegexOption.IGNORE_CASE),
    Regex("""\blowest\s+price\b""", RegexOption.IGNORE_CASE),
    Regex("""\bhot\s+deal\b""", RegexOption.IGNORE_CASE),
    Regex("""\btoday\s+only\b""", RegexOption.IGNORE_CASE),
    Regex("""\bends\s+(?:tonight|soon|today)\b""", RegexOption.IGNORE_CASE),
    Regex("""\bweekend\s+sale\b""", RegexOption.IGNORE_CASE),
    Regex("""\bsubscribe\s+and\s+save\b""", RegexOption.IGNORE_CASE),
    Regex("""\bfinal\s+hours\b""", RegexOption.IGNORE_CASE),
    Regex("""\bdoorbuster\b""", RegexOption.IGNORE_CASE),
    Regex("""\bhurry\b""", RegexOption.IGNORE_CASE),
    Regex("""\bwhile\s+supplies\s+last\b""", RegexOption.IGNORE_CASE),
    Regex("""\bonly\s+\$\d""", RegexOption.IGNORE_CASE),
    Regex("""\bfree\s+gift\b""", RegexOption.IGNORE_CASE),
    Regex("""\brewards?\s+(?:points|await)\b""", RegexOption.IGNORE_CASE),
    Regex("""\bvip\s+(?:access|sale)\b""", RegexOption.IGNORE_CASE),
    Regex("""[\x{1F300}-\x{1FAFF}]"""),
)

val UPDATES_SUBJECT_PATTERNS: List<Regex> = listOf(
    Regex("""\border(?:\s*#|\s+(?:confirm|number|placed|update))""", RegexOption.IGNORE_CASE),
    Regex("""\byour\s+order\b""", RegexOption.IGNORE_CASE),
    Regex("""\breceipt\b""", RegexOption.IGNORE_CASE),
    Regex("""\binvoice\b""", RegexOption.IGNORE_CASE),
    Regex("""\bpayment\b""", RegexOption.IGNORE_CASE),
    Regex("""\bshipped\b""", RegexOption.IGNORE_CASE),
    Regex("""\bshipping\b""", RegexOption.IGNORE_CASE),
    Regex("""\bout\s+for\s+delivery\b""", RegexOption.IGNORE_CASE),
    Regex("""\bdelivered\b""", RegexOption.IGNORE_CASE),
    Regex("""\bdelivery\b""", RegexOption.IGNORE_CASE),
    Regex("""\btracking\b""", RegexOption.IGNORE_CASE),
    Regex("""\bconfirm(ation|ed)?\b""", RegexOption.IGNORE_CASE),
    Regex("""\bbooking\b""", RegexOption.IGNORE_CASE),
    Regex("""\breservation\b""", RegexOption.IGNORE_CASE),
    Regex("""\bitinerary\b""", RegexOption.IGNORE_CASE),
    Regex("""\bboarding\s+pass\b""", RegexOption.IGNORE_CASE),
    Regex("""\bcheck[\s-]?in\b""", RegexOption.IGNORE_CASE),
    Regex("""\bappointment\b""", RegexOption.IGNORE_CASE),
    Regex("""\bstatement\b""", RegexOption.IGNORE_CASE),
    Regex("""\brenewal\b""", RegexOption.IGNORE_CASE),
    Regex("""\bsecurity\s+(?:alert|code|notification)\b""", RegexOption.IGNORE_CASE),
    Regex("""\bnew\s+(?:sign[\s-]?in|login|device)\b""", RegexOption.IGNORE_CASE),
    Regex("""\bverif(?:y|ication)\b""", RegexOption.IGNORE_CASE),
    Regex("""\bone[\s-]?time\s+(?:code|password|passcode)\b""", RegexOption.IGNORE_CASE),
    Regex("""\botp\b""", RegexOption.IGNORE_CASE),
    Regex("""\byour\s+code\s+is\b""", RegexOption.IGNORE_CASE),
    Regex("""\bpassword\s+(?:reset|changed)\b""", RegexOption.IGNORE_CASE),
    Regex("""\b2fa\b""", RegexOption.IGNORE_CASE),
    Regex("""\bsign[\s-]?in\b""", RegexOption.IGNORE_CASE),
    Regex("""\bsubscription\s+(?:renew|expir)""", RegexOption.IGNORE_CASE),
    Regex("""\baccount\s+(?:update|notice|alert)\b""", RegexOption.IGNORE_CASE),
    Regex("""\bterms\s+of\s+service\b""", RegexOption.IGNORE_CASE),
    Regex("""\bprivacy\s+policy\b""", RegexOption.IGNORE_CASE),
)

val FINANCE_SUBJECT_PATTERNS: List<Regex> = listOf(
    Regex("""\byour\s+statement\b""", RegexOption.IGNORE_CASE),
    Regex("""\baccount\s+balance\b""", RegexOption.IGNORE_CASE),
    Regex("""\btransaction\s+(?:alert|declined|approved)\b""", RegexOption.IGNORE_CASE),
    Regex("""\bpayment\s+(?:received|sent|due|failed)\b""", RegexOption.IGNORE_CASE),
    Regex("""\bautopay\b""", RegexOption.IGNORE_CASE),
    Regex("""\bdirect\s+deposit\b""", RegexOption.IGNORE_CASE),
    Regex("""\bwire\s+transfer\b""", RegexOption.IGNORE_CASE),
    Regex("""\btax\s+(?:document|form|refund)\b""", RegexOption.IGNORE_CASE),
    Regex("""\bcredit\s+score\b""", RegexOption.IGNORE_CASE),
    Regex("""\bfraud\s+alert\b""", RegexOption.IGNORE_CASE),
    Regex("""\bsuspicious\s+(?:activity|charge)\b""", RegexOption.IGNORE_CASE),
    Regex("""\blow\s+balance\b""", RegexOption.IGNORE_CASE),
    Regex("""\bportfolio\b""", RegexOption.IGNORE_CASE),
    Regex("""\bdividend\b""", RegexOption.IGNORE_CASE),
    Regex("""\bmortgage\b""", RegexOption.IGNORE_CASE),
    Regex("""\bloan\s+(?:payment|approved)\b""", RegexOption.IGNORE_CASE),
)

val TRAVEL_SUBJECT_PATTERNS: List<Regex> = listOf(
    Regex("""\bflight\s+(?:confirmation|itinerary|change|delay|cancell?ed)\b""", RegexOption.IGNORE_CASE),
    Regex("""\bcheck[\s-]?in\s+(?:now|open|reminder)\b""", RegexOption.IGNORE_CASE),
    Regex("""\bboarding\s+pass\b""", RegexOption.IGNORE_CASE),
    Regex("""\byour\s+trip\b""", RegexOption.IGNORE_CASE),
    Regex("""\byour\s+reservation\b""", RegexOption.IGNORE_CASE),
    Regex("""\byour\s+stay\b""", RegexOption.IGNORE_CASE),
    Regex("""\brental\s+car\b""", RegexOption.IGNORE_CASE),
    Regex("""\bgate\s+change\b""", RegexOption.IGNORE_CASE),
    Regex("""\bdeparture\b""", RegexOption.IGNORE_CASE),
    Regex("""\barrival\b""", RegexOption.IGNORE_CASE),
    Regex("""\byour\s+ride\b""", RegexOption.IGNORE_CASE),
    Regex("""\bdriver\s+(?:is\s+on\s+the\s+way|assigned)\b""", RegexOption.IGNORE_CASE),
    Regex("""\byour\s+order\s+is\s+on\s+its\s+way\b""", RegexOption.IGNORE_CASE),
    Regex("""\bfood\s+delivery\b""", RegexOption.IGNORE_CASE),
)

val SHOPPING_SUBJECT_PATTERNS: List<Regex> = listOf(
    Regex("""\brefund\s+(?:issued|processed)\b""", RegexOption.IGNORE_CASE),
    Regex("""\breturn\s+(?:label|confirmation)\b""", RegexOption.IGNORE_CASE),
    Regex("""\bprice\s+drop\b""", RegexOption.IGNORE_CASE),
    Regex("""\bback\s+in\s+stock\b""", RegexOption.IGNORE_CASE),
    Regex("""\bstill\s+in\s+your\s+cart\b""", RegexOption.IGNORE_CASE),
    Regex("""\bcart\s+is\s+waiting\b""", RegexOption.IGNORE_CASE),
    Regex("""\bwishlist\b""", RegexOption.IGNORE_CASE),
    Regex("""\bcoupon\b""", RegexOption.IGNORE_CASE),
    Regex("""\bpromo\s+code\b""", RegexOption.IGNORE_CASE),
)
