name: validate-fastlane-metadata

on:
  pull_request:
    paths:
      - 'fastlane/metadata/**'
  push:
    paths:
      - 'fastlane/metadata/**'

permissions:
  contents: read

jobs:
  validate-metadata:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - uses: ashutoshgngwr/validate-fastlane-supply-metadata@c8857fdbbd3e00f9a5cbe8604bcecfa95ce8fef8 # v2
        with:
          fastlaneDir: ./fastlane/metadata/android
